export type InventoryStockItem = {
  id: string;
  name: string;
  category: string;
  kind: string;
  subcategory?: string;
  size?: string;
  stock: number;
  reserved: number;
  assigned: number;
  unavailable: number;
  minStock: number;
  maxStock?: number | null;
  avgCost?: number;
  location?: string;
  unit?: string;
  photoUrl?: string;
  sku?: string;
  barcode?: string;
  description?: string;
  inventoryClass?: "consumable" | "sellable" | "reusable" | "asset";
  preferredSupplier?: string;
  requiresSerialTracking?: boolean;
  requiresLotTracking?: boolean;
  requiresExpiryTracking?: boolean;
  isCommercial?: boolean;
  isActive?: boolean;
  archivedAt?: string;
};
